### ISSUE TITLE
Ignoring Pod references

### ISSUE THREAD

**Issue by siggb** [vase4kin/SimpleApp#1]
Hey,
I would recommend you to include Pod directory to the .gitignore file. It is very common practice to not put those libs into your repository because you always can download them.

```
#Ignore CocoaPods files
/Pods
Podfile.*
```

Full .gitignore file could look like:

```
#Ignore the Mac OS X .DS_Store files
*.DS_Store*

#Ignore user-specific settings
*.mode1v3
*.mode2v3
*.pbxuser
*.perspectivev3
*xcuserdata*
*xcworkspace*

#Ignore CocoaPods files
/Pods
Podfile.*

#Ignore textmate build errors
*.tm_build_errors

#Ignore temp nibs and swap files
*.swp
*~.nib

#Ignore the build, since we don't want archived builds
build

.gitattributes

*.orig
DerivedData/*
```

**Comment by vase4kin** [comment]
Hi, pal!

Thanks for feedback, but that project is only for testing purposes. Next time i will follow your recommendations :)
